/**
 * Midnight Verify — Compiled Contract Bundle
 *
 * Wraps the real compiler-generated Contract class (compactc 0.31.0) into the
 * CompiledContract shape required by deployContract() from midnight-js-contracts.
 *
 * API verified by reading installed package types:
 *   @midnight-ntwrk/compact-js/dist/dts/effect/CompiledContract.d.ts
 *
 * Pattern:
 *   CompiledContract.make(tag, ContractConstructor)
 *   then pipe through:
 *   CompiledContract.withWitnesses(witnessObj)
 *   CompiledContract.withCompiledFileAssets('path/to/managed/age_verify')
 *
 * withWitnesses stores the object as-is and the runtime instantiates the
 * Contract as `new Contract(context.witnesses)` — so the witnesses object
 * must be passed directly (NOT wrapped as `{ witnesses }`).
 *
 * The compiledAssetsPath must point to the directory containing:
 *   keys/{circuitName}.prover
 *   keys/{circuitName}.verifier
 *   zkir/{circuitName}.zkir  (or .bzkir)
 *
 * These files were generated by: compact compile src/age_verify.compact
 */

import { pipe } from 'effect';
import * as CompiledContract from '@midnight-ntwrk/compact-js/effect/CompiledContract';
import {
  Contract,
  contractReferenceLocations,
  ledger,
  pureCircuits,
} from '@midnight-verify/contract';
import { createWitnessProvider } from '@midnight-verify/contract';
import type { AgeVerifyPrivateState } from '@midnight-verify/contract';
import { ZK_ASSETS_PATH } from './providers.js';

// ---------------------------------------------------------------------------
// The contract tag — uniquely identifies this contract type in the system.
// Used as a key in private state storage and contract registries.
// ---------------------------------------------------------------------------
const CONTRACT_TAG = 'midnight-verify/age-verify/v1';

// ---------------------------------------------------------------------------
// makeCompiledContract(age)
//
// Builds a fully configured CompiledContract ready for deployContract().
//
// The age parameter is used to build the witness. During deployment the age
// is set to 0n (placeholder) — the real age is provided by the user at the
// moment of the verifyAge circuit call, not at deployment time.
//
// compiledAssetsPath tells NodeZkConfigProvider where to find:
//   keys/verifyAge.prover, keys/verifyAge.verifier
//   keys/resetVerification.prover, etc.
//   zkir/verifyAge.zkir, etc.
// ---------------------------------------------------------------------------
export function makeCompiledContract(age: bigint = 0n) {
  const witnesses = createWitnessProvider({ secretAge: age });

  return pipe(
    // Step 1: bind the compiled Contract constructor to a tag
    CompiledContract.make(CONTRACT_TAG, Contract),
    // Step 2: supply witness implementations
    // CompactContext.Witnesses shape: the witnesses object itself
    CompiledContract.withWitnesses(witnesses),
    // Step 3: tell the system where to find prover/verifier keys and ZKIR
    CompiledContract.withCompiledFileAssets(ZK_ASSETS_PATH),
  );
}

// ---------------------------------------------------------------------------
// makeInitialPrivateState(age)
//
// Creates the initial private state for a deployment or circuit call session.
// The age stored here is the ONLY place the exact age exists in the system.
// ---------------------------------------------------------------------------
export function makeInitialPrivateState(age: bigint): AgeVerifyPrivateState {
  return { secretAge: age };
}

// ---------------------------------------------------------------------------
// Re-exports
// ---------------------------------------------------------------------------
export {
  contractReferenceLocations,
  ledger,
  pureCircuits,
  CONTRACT_TAG,
};
export type { AgeVerifyPrivateState };
