/**
 * Midnight Verify — Contract package public API
 *
 * Re-exports from the REAL compiler-generated output (compactc 0.31.0):
 *   src/managed/age_verify/contract/index.js  ← generated by compact compile
 *   src/managed/age_verify/contract/index.d.ts ← generated by compact compile
 *
 * Also exports application-level private state helpers (not compiler-generated):
 *   src/private-state.ts
 */

// ---------------------------------------------------------------------------
// Real compiler-generated exports
// Path: managed/age_verify/contract/ (written by compactc 0.31.0)
// ---------------------------------------------------------------------------
export {
  Contract,
  ledger,
  pureCircuits,
  contractReferenceLocations,
} from './managed/age_verify/contract/index.js';

export type {
  Witnesses,
  ImpureCircuits,
  ProvableCircuits,
  PureCircuits,
  Circuits,
  Ledger,
  ContractReferenceLocations,
} from './managed/age_verify/contract/index.js';

// ---------------------------------------------------------------------------
// Application-level private state helpers (NOT compiler-generated)
// ---------------------------------------------------------------------------
export {
  createPrivateState,
  createWitnessProvider,
} from './private-state.js';

export type { AgeVerifyPrivateState } from './private-state.js';
