/**
 * Midnight Verify — Private State Helpers
 *
 * These are application-level helpers, NOT generated by the Compact compiler.
 * They handle the private state that feeds into the witness function.
 *
 * Privacy contract:
 *   - secretAge stays ONLY in this private state object
 *   - It is read by the witness function (getAge) during circuit execution
 *   - It NEVER appears in the public ledger state
 *   - It NEVER leaves the user's local environment
 */

import type { WitnessContext } from '@midnight-ntwrk/compact-runtime';
import type { Ledger, Witnesses } from './managed/age_verify/contract/index.js';

// ---------------------------------------------------------------------------
// Private state shape
// ---------------------------------------------------------------------------

/**
 * Private state held locally by the wallet/application.
 * This is the only place the exact age exists in the system.
 */
export interface AgeVerifyPrivateState {
  /** The user's private age. Never disclosed on-chain. */
  readonly secretAge: bigint;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Create private state from a user-provided age.
 * The age is stored here and accessed via the witness during circuit execution.
 */
export function createPrivateState(age: bigint): AgeVerifyPrivateState {
  return { secretAge: age };
}

/**
 * Create a Witnesses object that reads the private age from private state.
 *
 * The `getAge` witness function:
 *   - Receives the WitnessContext (includes ledger state and private state)
 *   - Returns [updatedPrivateState, age]
 *   - This is the ONLY path through which the age reaches the ZK circuit
 */
export function createWitnessProvider(
  initialPrivateState: AgeVerifyPrivateState,
): Witnesses<AgeVerifyPrivateState> {
  return {
    getAge: (
      ctx: WitnessContext<Ledger, AgeVerifyPrivateState>,
    ): [AgeVerifyPrivateState, bigint] => {
      // Return the age from private state — it stays inside the ZK circuit
      return [ctx.privateState, ctx.privateState.secretAge];
    },
  };
}
